services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on: [rabbit, db]
    env_file:
      - .env

  worker:
    build: .
    command: celery -A app.interfaces.worker.celery_app worker --loglevel=info
    depends_on: [rabbit, db]

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"   # AMQP
      - "15673:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "55432:5432"
